### ISSUE TITLE
.vscode folders are usually ignored

### ISSUE THREAD

**Issue by BarchamMal** [kellyjohart/Assignment0#1]
I noticed that this repo happens to have a .vscode folder. This stores data and settings for Visual studio code. This could be done on purpose, but usually is not advised unless it is for important settings like for extensions which have different settings per workspace, etc.
To ignore the .vscode folder (but then you wouldn't keep the pink color, which happens to be the only thing saved in those settings 😄) you would add a line `.vscode` to the .gitignore and then any changes made to it would not be included in commits and PRs.

**Comment by kellyjohart** [comment]
Thanks much appreciated!

It didn’t occur to me until you mentioned it but come to think of it - In
the Java script lessons there was a mention about gitignores.- It differed
from each language/project type one would use I believe?  I’ll def look
into what else to ignore/how that works and/or add it to my list of Q&A for
class/checkins. 😁

**Comment by kellyjohart** [comment]
Correction (to my last message):

JAVA not Java script - and in the Eclipse program 😅. Sorry about that!
